version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "moicky-dynamodb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-141btx4jxi9e4"
s3_prefix = "moicky-dynamodb"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
