AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "@Moicky/dynamodb"

Resources:
  DefaultDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

  SecondDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: bookId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: bookId
          AttributeType: S

  TableWithGSIs:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: stars
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: booksByAuthor
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: booksByStars
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: stars
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  PlaygroundTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

Outputs:
  DefaultTableArn:
    Description: "DynamoDB Table Arn for tests"
    Value: !Ref DefaultDynamoDBTable
  SecondTableArn:
    Description: "DynamoDB Table Arn for tests"
    Value: !Ref SecondDynamoDBTable
  TableWithGSIsArn:
    Description: "DynamoDB Table Arn for tests"
    Value: !Ref TableWithGSIs
  PlaygroundTableArn:
    Description: "DynamoDB Table Arn for tests"
    Value: !Ref PlaygroundTable
