name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-central-1"
  DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: npm ci
      - run: npm run build
      - run: npm test
